### ISSUE TITLE
Not all files are exported

### ISSUE THREAD

**Issue by kvand137** [microsoft/Bio-Compliancy#6]
The script ran without issues but i'm not able to load the data into the powerbi template.

The readme states:
Één CSV file
Één PS1 file
Één PSD1 file
Drie JSON files

My export only contains:
ConfigurationData.psd1
M365Report.JSON
M365TenantConfig.ps1

Other files are not exported. How can i get all the other files?

**Comment by ykuijs** [comment]
Hi @kvand137, which scripts have you executed? It looks like the analysis script hasn't fully executed yet. Did you receive any errors during execution? Are you running the analysis on a Windows Client OS (Windows 10/11)?

**Comment by kvand137** [comment]
> Hi @kvand137, which scripts have you executed? It looks like the analysis script hasn't fully executed yet. Did you receive any errors during execution? Are you running the analysis on a Windows Client OS (Windows 10/11)?

Hi @ykuijs .\RunBIOExport.ps1 and .\RunBIOAssessment.ps1. I didn't receive any error and ran it on a windows 216 server.

**Comment by ykuijs** [comment]
Hi @kvand137, zou je mij een mail kunnen sturen op "ykuijs[at]microsoft.com". Dan kunnen we het issue troubleshooten

**Comment by kvand137** [comment]
Hi all, Thanks to @ykuijs we found the problem. The problem was in the chair not in the keyboard. I forget to run the  .\RunBIOAssessment.ps1 script on the day i ran the export. Reading issue. It is all working now. Thanks @ykuijs!!

**Comment by ykuijs** [comment]
You are welcome!
