### ISSUE TITLE
Power BI dashboard is 0% en leeg

### ISSUE THREAD

**Issue by PvErning** [microsoft/Bio-Compliancy#7]
Hallo,
De installatie stappen met succes doorlopen. De files zijn in de output netjes aanwezig, output:
Directory of D:\BIO_XXX\Bio-Compliancy-main\scripts\Output\20240828

08/28/2024  10:12 AM    <DIR>          .
08/28/2024  08:59 AM    <DIR>          ..
08/28/2024  09:45 AM             1,850 ConfigurationData.psd1
08/28/2024  10:02 AM                 2 M365Report.JSON
08/28/2024  09:45 AM        13,022,062 M365TenantConfig.ps1
08/28/2024  10:12 AM           137,412 Results_BIOControls.json
08/28/2024  10:12 AM            60,443 Results_BIOControlsOverview.csv
08/28/2024  10:12 AM            45,394 Results_Comparison.json
               6 File(s)     13,267,163 bytes
               2 Dir(s)  175,582,904,320 bytes free
D:\BIO_XXX\Bio-Compliancy-main\scripts\Output\20240828>

Wanneer we deze inlezen in power Bi, krijgen we ook geen fouten maar is het dashboard leeg en groen.
Helaas is dat niet de waarheid..

![bio](https://github.com/user-attachments/assets/d9b27f53-902f-4f92-9b05-1ed9ce928030)

**Comment by PvErning** [comment]
Prerequerment eerst inregelen, template inlezen

**Comment by PvErning** [comment]
Nogmaals alles doorgelopen, export is gevuld. Helaas blijft het dashboard leeg.

**Comment by ykuijs** [comment]
Hi @PvErning, zou je mij een mail kunnen sturen op "ykuijs[at]microsoft.com". Dan kunnen we het issue troubleshooten

**Comment by PvErning** [comment]
Bedankt voor de hulp Yorick. Wij hebben getest van W11 machine hier staat standaard een winrm niet aan.
Dit is nu toegevoegd aan de documentatie en alles werkt nu naar behoren. 

"Indien je gebruik maakt van een Windows client OS (Windows 10 of Windows 11):
Voer het volgende commando uit winrm quickconfig"
